name: pre-commit

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      PRE_COMMIT_HOME: .cache/pre-commit
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          # The pylint-odoo version we use here does not support python 3.10
          # https://github.com/OCA/oca-addons-repo-template/issues/80
          # Moreover the black version we use here depends on a version of typed_ast
          # that is not compatible with python 3.9.8.
          python-version: "3.9.7"
      - uses: actions/cache@v2
        with:
          path: .cache/pre-commit
          key: pre-commit-py39-${{ hashFiles('.pre-commit-config.yaml') }}
      - run: pip install pre-commit
      - run: pre-commit run -a --show-diff-on-failure
