[project]
name = "odoo-addons-oca-server-tools"
version = "18.0.20240917.0"
dependencies = [
    "odoo-addon-base_view_inheritance_extension>=18.0dev,<18.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
